name: test getting the version

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Get the tag name
      id: get_tag_name
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: Get the branch name
      id: get_branch_name
      run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF/refs\/heads\//}
      shell: bash
    - name: print versions
      run: |
        echo Tag is ${{ steps.get_tag_name.outputs.TAG_NAME }}
        echo Branch is ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
