name: test getting the version

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Get the tag name
      id: get_tag_name
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: Get the branch name
      id: get_branch_name
      run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF/refs\/heads\//}
      shell: bash
    - name: print versions
      run: |
        echo Tag is ${{ steps.get_tag_name.outputs.TAG_NAME }}
        echo Branch is ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
    - name: Create Release package Linux
      if: matrix.os == 'ubuntu-latest'
      env:
        package_name: my_name-${{ steps.get_branch_name.outputs.BRANCH_NAME }}
      run: |
        mkdir test
        echo bla > test/file.txt
        mv test ${package_name}
        tar -cvzf ${package_name}.tgz ./${package_name}
    - name: Create Release package Linux
      if: matrix.os == 'windows-latest'
      env:
        package_name: my_name-${{ steps.get_branch_name.outputs.BRANCH_NAME }}
      run: |
        mkdir test
        echo bla > test\file.txt
        Rename-Item test %package_name%
        7z a -tzip %package_name%.zip %package_name%

        

