name: test getting the version

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Get the tag version
      id: get_tag_version
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
    - name: Get the branch name
      id: get_name_version
      run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF/refs\/heads\//}
    - name: print versions
      run: |
        echo Tag is ${{ steps.get_version.outputs.TAG_NAME }}
        echo Branch is ${{ steps.get_version.outputs.BRANCH_NAME }}
