name: test getting the version

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Get the tag name
      id: get_tag_name
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: print versions
      run: |
        echo Tag is ${{ steps.get_tag_name.outputs.TAG_NAME }}
#        echo Branch is ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
    - name: Create Release package Linux
      if: matrix.os == 'ubuntu-latest'
      env:
        package_name: my_name-linux-${{ steps.get_tag_name.outputs.TAG_NAME }}
      run: |
        mkdir test
        echo bla > test/file.txt
        mv test ${package_name}
        tar -cvzf ${package_name}.tgz ./${package_name}
        ls -la
    - name: Create Release package Windows
      if: matrix.os == 'windows-latest'
      env:
        package_name: my_name-windows-${{ steps.get_tag_name.outputs.TAG_NAME }}
      run: |
        mkdir test
        echo bla > test\file.txt
        Rename-Item test "${env:package_name}"
        7z a -tzip "${env:package_name}.zip" "${env:package_name}"
        dir
    - name: Upload binaries to release Linux
      if: matrix.os == 'ubuntu-latest'
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: my_name-linux-${{ steps.get_tag_name.outputs.TAG_NAME }}.tgz
        asset_name: my_name-linux-${{ steps.get_tag_name.outputs.TAG_NAME }}
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload binaries to release Windows
      if: matrix.os == 'windows-latest'
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: my_name-windows-${{ steps.get_tag_name.outputs.TAG_NAME }}.zip
        asset_name: my_name-windows-${{ steps.get_tag_name.outputs.TAG_NAME }}
        tag: ${{ github.ref }}
        overwrite: true
