name: test getting the version from tag

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'windows-2016', 'ubuntu-latest']
        include:
          - os: windows-latest
            cmake_generator: 'Visual Studio 16 2019'
            arch_key: '-A'
            arch_value: 'x64'
            toolset_key: '-T'
            toolset_value: 'v141'
            compress_cmd: '7z a -tzip "${env:package_name}.zip" "${env:package_name}"'
            compressed_suffix: 'zip'
            list_dir_cmd: 'dir'
          - os: windows-2016
            cmake_generator: 'Visual Studio 15 2017'
            arch_key: '-A'
            arch_value: 'x64'
            toolset_key: '-T'
            toolset_value: 'v140'
            compress_cmd: '7z a -tzip "${env:package_name}.zip" "${env:package_name}"'
            compressed_suffix: 'zip'
            list_dir_cmd: 'dir'
          - os: ubuntu-latest
            cmake_generator: 'Unix Makefiles'
            arch_key: ''
            arch_value: ''
            toolset_key: ''
            toolset_value: ''
            compress_cmd: 'tar -cvzf ${package_name}.tgz ./${package_name}'
            compressed_suffix: 'tgz'
            list_dir_cmd: 'ls -la'
    
    steps:
    - uses: actions/checkout@v1
    - name: Get the tag name
      id: get_tag_name
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: print versions
      run: |
        echo Tag is ${{ steps.get_tag_name.outputs.TAG_NAME }}
#        echo Branch is ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
    - name: Create Release package
      env:
        package_name: my_name-${{ matrix.os }}-${{ matrix.arch_value }}-${{ matrix.toolset_value }}-${{ steps.get_tag_name.outputs.TAG_NAME }}
      run: |
        mkdir my_name-${{ matrix.os }}-${{ matrix.arch_value }}-${{ matrix.toolset_value }}-${{ steps.get_tag_name.outputs.TAG_NAME }}
        echo test >  my_name-${{ matrix.os }}-${{ matrix.arch_value }}-${{ matrix.toolset_value }}-${{ steps.get_tag_name.outputs.TAG_NAME }}/file.txt
        ${{ matrix.compress_cmd }}
        ${{ matrix.list_dir_cmd }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: my_name-${{ matrix.os }}-${{ matrix.arch_value }}-${{ matrix.toolset_value }}-${{ steps.get_tag_name.outputs.TAG_NAME }}.${{ matrix.compressed_suffix }}
        asset_name: my_name-${{ matrix.os }}-${{ matrix.arch_value }}-${{ matrix.toolset_value }}-${{ steps.get_tag_name.outputs.TAG_NAME }}
        tag: ${{ github.ref }}
        overwrite: true

